version: "2.1"
services:
  code-server:
    container_name: clumsy-png_code-server
    build: 
      context: .
      dockerfile: code-server.dockerfile
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DEFAULT_WORKSPACE=/home/clumsy-png
      - SUDO_PASSWORD=password
    volumes:
      - .:/home/clumsy-png
      - ./.code-server:/config
    ports:
      - 8444:8443
    restart: unless-stopped